### ISSUE TITLE
Traceback error when attempting to run

### ISSUE THREAD

**Issue by ryanreis333** [mariaruizortega94/HLAGuessr#1]
Hi, thank you for developing this and making it available. I have some VDJ seq data I'm hoping to use this on, but I can't seem to figure out where I'm going wrong with it. It seems like I'm able to get it installed correctly in a conda env, but when I go to run it, I get the following error message:

Traceback (most recent call last):
  File "/home/user/.conda/envs/hlaguessr/bin/HLAGuessr-infer_hla", line 8, in <module>
    sys.exit(main())
  File "/home/user/.conda/envs/hlaguessr/lib/python3.6/site-packages/HLAGuessr/infer_hla.py", line 85, in main
    if options.infile_name is None:
AttributeError: 'Values' object has no attribute 'infile_name'

This is what I am currently running, replacing user with my username: 
~$ HLAGuessr-infer_hla -a ~user/alpha_data.tsv -b ~user/beta_data.tsv

It seems like it is attempting to run and finding the files fine, so any help on what I'm seeing now would be much appreciated! Thank you

**Comment by Marcus-Mendes** [comment]
I am having the same error. But I am not using conda. I tried my own dataset and the example dataset and none of them work.

**Comment by ryanreis333** [comment]
> I am having the same error. But I am not using conda. I tried my own dataset and the example dataset and none of them work.

Thanks for adding in a word, Marcus. Glad to hear I'm not the only one with this issue -- I'm thinking it's maybe something related to a change in one of the underlying python packages HLAGuessr relies on?

**Comment by dennis-serum** [comment]
> Hi, thank you for developing this and making it available. I have some VDJ seq data I'm hoping to use this on, but I can't seem to figure out where I'm going wrong with it. It seems like I'm able to get it installed correctly in a conda env, but when I go to run it, I get the following error message:
> 
> Traceback (most recent call last): File "/home/user/.conda/envs/hlaguessr/bin/HLAGuessr-infer_hla", line 8, in sys.exit(main()) File "/home/user/.conda/envs/hlaguessr/lib/python3.6/site-packages/HLAGuessr/infer_hla.py", line 85, in main if options.infile_name is None: AttributeError: 'Values' object has no attribute 'infile_name'
> 
> This is what I am currently running, replacing user with my username: ~$ HLAGuessr-infer_hla -a ~user/alpha_data.tsv -b ~user/beta_data.tsv
> 
> It seems like it is attempting to run and finding the files fine, so any help on what I'm seeing now would be much appreciated! Thank you

You need to define the `-d DELIMITER` option.

**Comment by chvandorp** [comment]
I know this is an old issue, but I just ran into this. I hope @mariaruizortega94 can fix this.

The issue only occurs if you don't use the `-d` option. If you add `-d tab` (as in the example in the README), then the exception is not raised. This is because of this piece of code in `infer_hla.py`:

```python
# Parse delimiter
    delimiter = options.delimiter
    if delimiter is None: #Default case
        if options.infile_name is None:
            delimiter = '\t'
        elif infile_name.endswith('.tsv'): # parse TAB separated value file
            delimiter = '\t'
        elif infile_name.endswith('.csv'): # parse COMMA separated value file
            delimiter = ','
    else:
        try:
            delimiter = {'tab': '\t', 'space': ' ', ',': ',', ';': ';', ':': ':'}[delimiter]
        except KeyError:
            pass # Other string passed as the delimiter.
```
Here the code tries to access `options.infile_name` if `delimiter is None` (i.e. when the used does not provide it). I guess `options.infile_name` has to be replaced with `infile_name`. 

Hope this helps!
